version: "3.8"
services:  
   shop:
    build: .
    environment:
      BOT_TOKEN: $BOT_TOKEN
      API_ID: $API_ID
      API_HASH: $API_HASH
      CHANNELS: $CHANNELS
      ADMINS: $ADMINS
      PICS: $PICS
      LOG_CHANNEL: $LOG_CHANNEL
      AUTH_USER: $AUTH_USER
      AUTH_CHANNEL: $AUTH_CHANNEL
      DATABASE_URI: $DATABASE_URI
      DATABASE_NAME: $DATABASE_NAME
      COLLECTION_NAME: $COLLECTION_NAME
      
